# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(400, 720)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(10, 5, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.name.setFont(font)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 40, 371, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(20, 360, 361, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.btn_run = QtWidgets.QPushButton(self.centralwidget)
        self.btn_run.setGeometry(QtCore.QRect(110, 300, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_run.setFont(font)
        self.btn_run.setObjectName("btn_run")
        self.btn_run.setEnabled(False)
        self.result_box = QtWidgets.QTextBrowser(self.centralwidget)
        self.result_box.setGeometry(QtCore.QRect(20, 400, 361, 291))
        self.result_box.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.result_box.setObjectName("result_box")
        self.as_txt = QtWidgets.QCheckBox(self.centralwidget)
        self.as_txt.setGeometry(QtCore.QRect(30, 260, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.as_txt.setFont(font)
        self.as_txt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.as_txt.setObjectName("as_txt")
        self.file_path = QtWidgets.QLineEdit(self.centralwidget)
        self.file_path.setGeometry(QtCore.QRect(20, 210, 241, 31))
        self.file_path.setObjectName("file_path")
        self.file = QtWidgets.QPushButton(self.centralwidget)
        self.file.setGeometry(QtCore.QRect(270, 210, 101, 31))
        self.file.setObjectName("file")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 70, 360, 110))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(r"img.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "EasyOCR"))
        self.name.setText(_translate("mainWindow", "Simple image to text converter"))
        self.btn_run.setText(_translate("mainWindow", "Run"))
        self.result_box.setText(_translate("mainWindow", "See result here..."))
        self.as_txt.setText(_translate("mainWindow", " Save as .txt"))
        self.file.setText(_translate("mainWindow", "File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
